Communications: domain mgmt of matrix ID
alkem-io/server pull request #1457
Opened 2021-10-11 18:51 UTC by techsmyth

One way mapping from email to communication ID i.e. Matrix. Bi-directional cannot be guaranteed so we cannot build on a 1-1 mapping. 

Code simplified to rely on domain model mgmt of communication ID.

Migration added to add the communicationID field to the user entity

2021-10-13 13:44 UTC, Enderedne submitted a review, later dismissed

2021-10-13 13:44 UTC, Enderedne commented on src/services/platform/communication/communication.dto.message.received.ts
> +  // TODO: is this needed? Should it not just be the user ID?
Related to the change in `src/services/platform/matrix/events/matrix.event.adapter.room.ts`.

This is going to break the subscriptions. Will address this in my commit.

2021-10-13 13:44 UTC, Enderedne commented on src/services/platform/communication/communication.service.ts
> +        mappedDirectRoomId, // may need to convert from an matrix ID to matrix username
Should be as it is. Will change the name to make it clearer

2021-10-14 09:26 UTC, valentinyanakiev requested changes
Comments inline, main areas:
- naming / types can be improved in a couple of places
- async registration of users fails - needs to be fixed
- we need to pick UsarAgent communicationsID and authorization service - can be done separately.

2021-10-14 09:26 UTC, valentinyanakiev commented on src/domain/community/user/user.service.ts
> +    this.communicationService.tryRegisterNewUser(user.email).then(
I believe this fails the bootstrap process. I don't believe the promise rejection is handled properly. See the screenshot:
![image](https://user-images.githubusercontent.com/7090348/137284384-856f71d1-ef55-411e-a65e-d5f49b6106d6.png)

2021-10-14 09:26 UTC, valentinyanakiev commented on src/domain/community/user/user.service.ts
> +    this.communicationService.tryRegisterNewUser(user.email).then(
Easy to reproduce - drop alkemio db, drop homeserver db, restart synapse server, run alkemio migrations, start. Reproducible 100%

2021-10-14 09:26 UTC, valentinyanakiev commented on src/domain/community/user/user.resolver.subscriptions.ts
> +      return payload.userID === context.req?.user?.communicationID;
That's a bit misleading, the userID in the context of matrix is matrix ID and the type defines it as the email of the user, but that is not the email of the user profile, but the matrix ID, as far as I see. Also the user context has both the user email and theh communications ID and you pick the communicationID and compare it with a property called userID - that's extremely confusing. I suggest CommunicationMessageReceived type to be changed to replace userID with matrixID, if I understand this logic correctly.

2021-10-14 09:26 UTC, valentinyanakiev commented on src/core/authentication/agent-info.ts
> +  communicationID = '';
In my opinion, this should not be here in the final design. The AgentInfo should have properties only from the user account payload (kratos traits in our case) and credentials.

2021-10-14 09:26 UTC, valentinyanakiev commented on src/domain/community/user/user.service.ts
> +  async populateRoomMessageSenders(rooms: (CommunityRoom | DirectRoom)[]) {
I believe in this case (CommunityRoom | DirectRoom) can be CommunityRoom only, as DirectRoom extends CommunityRoom.

2021-10-15 09:41 UTC, Enderedne commented on src/domain/community/user/user.service.ts
> +    this.communicationService.tryRegisterNewUser(user.email).then(
Traced that down to incorrect HMAC - this means that the registration_shared_secret might not be the same, or a different sort of configuration issue.

2021-10-15 14:31 UTC, techsmyth commented on src/domain/community/user/user.resolver.subscriptions.ts
> +      return payload.userID === context.req?.user?.communicationID;
Addressed

2021-10-18 08:31 UTC, Enderedne reviewed
Nothing major, but since we spent time making the code base more consistent,  I thought it would be good to highlight those changes.

2021-10-18 08:31 UTC, Enderedne commented on src/domain/community/user/user.interface.ts
> +  serviceProfile!: boolean;
I don't understand what does this have to do with matrix?

2021-10-18 08:31 UTC, Enderedne commented on src/services/platform/matrix/events/matrix.event.adapter.room.ts
> +            communicationID: message.receiverID,
This is matrixId when we are in the scope of matrix. It should remain matrixId. Further down the line it could be wrapped in communicationId, but right now this makes things more complicated and we're adding domain definition inside of the platform one.

2021-10-18 08:31 UTC, Enderedne commented on src/services/platform/matrix/agent/matrix.agent.service.ts
> +      room.receiverCommunicationsID =
The same concern mentioned below about using communicationId vs matrixId

2021-10-18 08:31 UTC, Enderedne commented on src/services/platform/matrix/adapter-message/matrix.message.adapter.service.ts
> +export class MatrixMessageAdapterService {
The structure will do the fine for now but will be reworked entirely when we get to message editing.

2021-10-18 09:02 UTC, valentinyanakiev commented
Still doesn't work for me, same reproduction steps, different error.

1. Drop alkemio db.
2. Create empty alkemio db.
3. Run migrations.
4. Drop (delete) homeserver.db.
5. Restart synapse server container.
6. Enable communications (COMMUNICATIONS_ENABLED=true in .env)
7. Start the server (npm start)

![image](https://user-images.githubusercontent.com/7090348/137701240-af0e903d-3c62-468b-aef8-bf54c2ab0d3e.png)

It's 100% reproducible for me/

2021-10-18 09:14 UTC, techsmyth commented
> Still doesn't work for me, same reproduction steps, different error.
> 
> 1. Drop alkemio db.
> 2. Create empty alkemio db.
> 3. Run migrations.
> 4. Drop (delete) homeserver.db.
> 5. Restart synapse server container.
> 6. Enable communications (COMMUNICATIONS_ENABLED=true in .env)
> 7. Start the server (npm start)
> 
> ![image](https://user-images.githubusercontent.com/7090348/137701240-af0e903d-3c62-468b-aef8-bf54c2ab0d3e.png)
> 
> It's 100% reproducible for me/

should now be fixed; can you please try again?

2021-10-18 10:45 UTC, valentinyanakiev approved these changes

2021-10-18 10:46 UTC, valentinyanakiev commented
Hold off merging until we increase the defaults on infra-ops

2021-10-18 11:38 UTC, merged