Community entity extended to know the type and parent ID
alkem-io/server pull request #1501
Opened 2021-10-29 09:13 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-10-29 13:02 UTC, valentinyanakiev requested changes
Please find comments inline - there are some changes required. We need to discuss hub community approach as well.

2021-10-29 13:02 UTC, valentinyanakiev commented on src/domain/challenge/ecoverse/ecoverse.service.ts
>      // set the credential type in use by the community
Why aren't you setting the ecoverse.community.parentID to the ecoverse.id here?

2021-10-29 13:02 UTC, valentinyanakiev commented on src/domain/community/community/community.entity.ts
> +  parentID: string;
Isn't the community always supposed to have parentID?

2021-10-29 13:02 UTC, valentinyanakiev commented on src/domain/community/community/community.interface.ts
> +  parentID?: string;
Isn't the community always supposed to have parentID?

2021-10-29 13:02 UTC, valentinyanakiev commented on src/domain/community/community/community.resolver.mutations.ts
> +    if (community.type === CommunityType.CHALLENGE) {
Extract this logic in a method (at least one). It will make the code more readable and this is (building the payload) is a logical block that can easily be extracted.

2021-10-29 13:02 UTC, valentinyanakiev commented on src/migrations/1635431556279-community-type-parentid.ts
> +      'ALTER TABLE `community` ADD `type` varchar(255) NOT NULL'
255 characters here is excessive for fields with constant lengths.

2021-10-29 15:12 UTC, techsmyth requested changes
Good to see you working through all aspects of this extension!

2021-10-29 15:12 UTC, techsmyth commented on src/common/enums/community.type.ts
> +registerEnumType(CommunityType, {
This does not need to be explosed on the graphql qpi

2021-10-29 15:12 UTC, techsmyth commented on src/domain/community/community/community.interface.ts
> +  @Field(() => String, {
The adding of these fields was for usage within the server. I have not heard a use case to expose on the graphql api. Would then make any of the logic on the client easier?

2021-10-29 15:12 UTC, techsmyth commented on src/migrations/1635431556279-community-type-parentid.ts
> +      'ALTER TABLE `community` ADD `type` varchar(255) NOT NULL'
This should also be fixed in the entity definition?

2021-11-01 10:17 UTC, techsmyth approved these changes
Changes look good, thanks!

2021-11-01 12:14 UTC, valentinyanakiev approved these changes

2021-11-01 12:14 UTC, merged