User preferences + update
alkem-io/server pull request #1536
Opened 2021-11-16 09:45 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2021-11-19 13:18 UTC, techsmyth requested changes
Nice domain model extension.

There are some awaits / messages that need addressing. Nothing structural, just tidy ups.

2021-11-19 13:18 UTC, techsmyth commented on src/core/bootstrap/bootstrap.service.ts
> +        'No users section in the authorization bootstrap file!',
Message needs updating

2021-11-19 13:18 UTC, techsmyth commented on src/core/bootstrap/bootstrap.service.ts
> +        `Unable to create profiles ${(err as Error).message}`
message here also needs updating

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/dto/user-preference-definition.dto.create.ts
> +import { UserPreferenceType, UserPreferenceValueType } from '@src/common';
dangerous to import from the top level index file; will cause issues. Please import the types from teh actual folder.

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +    return this.definitionRepository.save(definition);
await?

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +    return this.preferenceRepository.save(newPreferences);
await?

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +    const newPreferences = this.preferenceRepository.create(prefInputs);
await?

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +        `Unable to find preference for user with ID: ${user.id}`,
Message should also state which type of preference could not be found.

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +      return this.preferenceRepository.save(preference);
await...

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.service.ts
> +    return this.definitionRepository.find();
method should be async, and the find call awaited...

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user-preferences/utils.ts
> +import { UserPreferenceValueType } from '@src/common';
dangerous import, please import directly from the file

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user/user.interface.ts
> +  @Field(() => [IUserPreference], {
There is a field resolver for this, so it is not needed in the interface definition to also specify the field decorator

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user/user.interface.ts
> +    nullable: true,
This list is not nullable, though it may be empty.

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user/user.resolver.fields.ts
> +    return this.userService.getPreferences(user.id);
am pretty sure this method is async and should be awaited, which also means the field resolver should be async

2021-11-19 13:18 UTC, techsmyth commented on src/domain/community/user/user.resolver.mutations.ts
> +    return this.preferenceService.updateUserPreference(
await...

2021-11-22 07:18 UTC, hero101 commented on src/domain/community/user-preferences/user.preference.service.ts
> +    const newPreferences = this.preferenceRepository.create(prefInputs);
it's synchronous

2021-11-22 10:23 UTC, techsmyth reviewed
Updates after review look good, still need to try the code out...

2021-11-22 11:01 UTC, techsmyth requested changes
A few comments on follow up review...

2021-11-22 11:01 UTC, techsmyth commented on src/domain/community/user-preferences/dto/user-preference.dto.update.ts
> +import { UserPreferenceType } from '@src/common';
still a dangerous import...

2021-11-22 11:01 UTC, techsmyth commented on src/domain/community/user-preferences/user.preference.definition.interface.ts
> +import { UserPreferenceType, UserPreferenceValueType } from '@src/common';
and another dangerous import

2021-11-22 11:01 UTC, techsmyth commented on src/migrations/1636644627179-user-preferences.ts
> +      `CREATE TABLE \`alkemio\`.\`user_preference_definition\` (\`id\` char(36) NOT NULL, \`createdDate\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedDate\` datetime(6) NOT NULL DEFAU
the table name should not be included

2021-11-22 16:18 UTC, techsmyth requested changes
Afraid something went wrong with the latest migration:
![image](https://user-images.githubusercontent.com/30729240/142896803-496a6211-8e90-458b-8510-9b6509d7725b.png)

steps followed: 
new db
checkout develop
run migrations
start server so users are created
checkout server-1410
run migrations
error as above...

2021-11-24 07:12 UTC, techsmyth requested changes
Migration works nicely now!

I extended the set of notifications to be what I think we will be releasing for the 13th, works as before as far as I can tell but please do check.

Two additional comments:
- AuthorizationPolicy is not being set properly on the UserPreference entity after migration:
![image](https://user-images.githubusercontent.com/30729240/143191587-be7567e9-72ef-4816-a096-9a1bbf033d3d.png)
it should not be null but point to a created AuthorizationPolicy
- The authorizationDefinition does not need to be authorizable. It should derive from IBaseAlkemio instead of IAuthorizable

2021-11-24 12:04 UTC, techsmyth approved these changes
working nicely!

2021-11-24 12:37 UTC, merged