Notification group rename
alkem-io/server pull request #1666
Opened 2022-01-14 11:58 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-01-16 11:57 UTC, techsmyth submitted a review, later dismissed
Makes sense from a code perspective.

2022-01-17 14:54 UTC, valentinyanakiev requested changes
Migration is not working, see code suggestions. You are searching by the enum key, and should be searching by the value.

2022-01-17 14:54 UTC, valentinyanakiev commented on src/migrations/1642159571969-pref-definition-groups-rename.ts
> +            where type in ('NOTIFICATION_COMMUNICATION_DISCUSSION_CREATED_ADMIN', 'NOTIFICATION_COMMUNICATION_UPDATE_SENT_ADMIN', 'NOTIFICATION_APPLICATION_RECEIVED')
```suggestion
            where type in ('NotificationCommunityDiscussionCreatedAdmin', 'NotificationCommunityUpdateSentAdmin', 'NotificationApplicationReceived')
```

2022-01-17 14:54 UTC, valentinyanakiev commented on src/migrations/1642159571969-pref-definition-groups-rename.ts
> +            where type = 'NOTIFICATION_USER_SIGN_UP'
```suggestion
            where type = 'NotificationUserSignUp'
```

2022-01-18 09:08 UTC, valentinyanakiev approved these changes

2022-01-18 09:59 UTC, merged