allow updating of hub nameID
alkem-io/server pull request #1680
Opened 2022-01-21 12:49 UTC by techsmyth

2022-01-24 11:57 UTC, valentinyanakiev requested changes

2022-01-24 11:57 UTC, valentinyanakiev commented on src/domain/challenge/ecoverse/ecoverse.service.ts
> +        await this.ecoverseRepository.save(ecoverse);
This line is redundant, you already save it on line 136.

2022-01-24 11:58 UTC, valentinyanakiev commented on src/domain/challenge/ecoverse/ecoverse.service.ts
> +        await this.ecoverseRepository.save(ecoverse);
```suggestion
```

2022-01-24 13:11 UTC, techsmyth commented on src/domain/challenge/ecoverse/ecoverse.service.ts
> +        await this.ecoverseRepository.save(ecoverse);
Addressed

2022-01-27 11:42 UTC, valentinyanakiev approved these changes

2022-01-27 11:43 UTC, merged