Added filter to the pagination api
alkem-io/server pull request #1895
Opened 2022-04-28 14:28 UTC by hero101

## This is dependent on #1893.

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-04-29 07:18 UTC, me-andre submitted a review, later dismissed

2022-04-29 07:18 UTC, me-andre commented on src/domain/community/user/user.service.ts
> +    // eslint-disable-next-line @typescript-eslint/no-unused-vars
are you sure you need this exception? `filter` seems to be used in the fn body.

2022-04-29 13:41 UTC, Comoque1 commented
Missing error messages for organizationPagination for preferences and groups
![image](https://user-images.githubusercontent.com/23620658/165956089-7f9b19a1-5b42-4afe-9b3e-91d0acf8db12.png)

2022-04-29 13:43 UTC, Comoque1 commented
Add validation for invalid pagination values
![image](https://user-images.githubusercontent.com/23620658/165956305-6c1d8fff-9e7d-4ea1-be01-f768f0153802.png)

2022-04-29 14:40 UTC, valentinyanakiev approved these changes
Looks good for building this further:
- rowID can be in the base alkemio interface (or alternatively in another base interface, but I think having SEED column everywhere is always beneficial).
- the SEED column rowID should be unsigned, and ideally UNSIGNED MEDIUMINT. It can't be negative. And int accommodates way more than needed anyway.
- how filtering is done should examined in the future (specific filters). Lookgs OK for now with LIKE.
- there are some functions (e.g. getRelayStylePaginationResults) that should be split as they are a bit too long.

Other than that, good approach and implementation :) Kudos.

2022-05-03 08:36 UTC, Comoque1 commented
Missing error message for `phone`
![image](https://user-images.githubusercontent.com/23620658/166425311-6fac3f12-e966-4259-a284-8b90646e82c4.png)

2022-05-04 08:02 UTC, valentinyanakiev requested changes
Check the [CI](https://app.travis-ci.com/github/alkem-io/server/builds/250037086), it seems you have missed an export

2022-05-04 13:57 UTC, valentinyanakiev approved these changes

2022-05-04 13:58 UTC, merged