WIP: TemplatesSet + AspectTemplates
alkem-io/server pull request #1956
Opened 2022-05-26 16:46 UTC by techsmyth

Work in progress.

New entity: TemplatesSet
New entity: AspectTemplate
New base entity: TemplateBase

Partial migration to make the data storage + relationships work. 

Sample mutations to add / remove an AspectTemplate from a TemplatesSet.

Todo:
- migrate existing data
- add in default set of AspectTemplates for a new Hub
- Remove notion of aspect templates from UX configuration file
- remove old template field + support from mutations / DTO in Hub
- fill out set of fields in BaseTemplate entity
- fill out set of fields in AspectTemplate entity (specific to aspects)

2022-06-09 16:03 UTC, valentinyanakiev requested changes
This feels like work in progress to me, see comments inline:

- data migration is incorrect and leads to data replication
- data types / dtos don't match
- canvases won't work with this setup as DTO size is not applied here
- one of the samples (delete-aspect-template) is wrong, and delete-canvas-template is overall missing
- template.set.resolver.mutations.ts actually contains aspect template and canvas template mutations and no templatesset mutations. It makes sense to an extent given all canvases are part of a templatesset, but in my opinion logically this is aspect / canvas template mutations. Templatesset mutations would be to alter the state of a templates set, and we don't have that at all. At the same time the canvas/aspect.template.resolver.mutations.ts are left out empty.
- There are dead DTOs in the code that are not being used by any mutation

I believe these all need addressing before going further with the review of the services.

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/aspect-template/dto/aspect.template.dto.update.ts
> +  type!: string;
512 characters for type is excessive

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/aspect-template/dto/aspect.template.dto.update.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
8196 characters for description is again excessive

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/canvas-template/dto/canvas.template.dto.create.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
We need the canvas length here

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/canvas-template/dto/canvas.template.dto.update.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
CANVAS_LENGTH again

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/template-base/dto/template.base.dto.create.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
We don't need 8196 characters for description

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/template-base/dto/template.base.dto.update.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
We don't need 8196 characters for description

2022-06-09 16:03 UTC, valentinyanakiev commented on src/domain/template/template-base/template.base.service.ts
> +      baseTemplate.tagset.tags = baseTemplateData.tags;
Do we want to override instead of merge?

2022-06-09 16:03 UTC, valentinyanakiev commented on src/migrations/1653580239006-templatesSet.ts
> +              \`version\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`templatesSetId\` char(36) NULL, \`tagsetId\` char(36) NULL, \`visualId\` char(36) NULL,
title is SMALL_TEXT_LENGTH (128) in the DTO. It doesn't make sense to have it twice as long in the DB.

2022-06-09 16:03 UTC, valentinyanakiev commented on src/migrations/1653580239006-templatesSet.ts
> +      if (existingTemplate) {
Existing template migration is incorrect and leads to duplicate data logically. For me, the combination of title+type+description defines an aspect. Real data migration leads to something like:

![image](https://user-images.githubusercontent.com/7090348/172887836-bafdb386-1514-44bd-92fc-951b8c287606.png)

2022-06-09 16:03 UTC, valentinyanakiev commented on src/migrations/1653580239006-templatesSet.ts
> +              \`version\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`templatesSetId\` char(36) NULL, \`tagsetId\` char(36) NULL, \`visualId\` char(36) NULL,
again, title 128 vs 255

2022-06-09 16:03 UTC, valentinyanakiev commented on graphql-samples/mutations/delete/delete-aspect-template
> +mutation deleteAspectTemplate($deleteData: DeleteAspectTemplateInput!) {
this sample is wrong:

![image](https://user-images.githubusercontent.com/7090348/172890061-1827c0c2-9d8a-4e15-b011-59b641c13517.png)

2022-06-10 06:32 UTC, techsmyth commented on src/domain/template/aspect-template/dto/aspect.template.dto.update.ts
> +  type!: string;
Agreed, resolved

2022-06-10 06:32 UTC, techsmyth commented on src/domain/template/aspect-template/dto/aspect.template.dto.update.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
Agreed, made LONG TEXT LENGTH

2022-06-10 06:33 UTC, techsmyth commented on src/domain/template/canvas-template/dto/canvas.template.dto.update.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
Agreed, updated

2022-06-10 06:33 UTC, techsmyth commented on src/domain/template/template-base/dto/template.base.dto.create.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
Agreed, updated to be LONG TEXT LENGTH

2022-06-10 06:33 UTC, techsmyth commented on src/domain/template/template-base/template.base.service.ts
> +      baseTemplate.tagset.tags = baseTemplateData.tags;
Yes, that is how we do tag updates everywhere

2022-06-10 06:34 UTC, techsmyth commented on src/migrations/1653580239006-templatesSet.ts
> +              \`version\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`templatesSetId\` char(36) NULL, \`tagsetId\` char(36) NULL, \`visualId\` char(36) NULL,
Agreed, updated.

2022-06-10 06:36 UTC, techsmyth commented on src/migrations/1653580239006-templatesSet.ts
> +      if (existingTemplate) {
This is by design. We discussed that we would use copy on instantiate, and the logical implication of this is that the database will have lots of the default template types. The alternative is to have referential integrity, which brings with it that there needs to be logic to know when it is a shared template and when it is just for the hub using it. The design choice is in the MD file. Happy to discuss.

2022-06-10 06:36 UTC, techsmyth commented on src/migrations/1653580239006-templatesSet.ts
> +              \`version\` int NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`templatesSetId\` char(36) NULL, \`tagsetId\` char(36) NULL, \`visualId\` char(36) NULL,
Agreed

2022-06-10 06:36 UTC, techsmyth commented on graphql-samples/mutations/delete/delete-aspect-template
> +mutation deleteAspectTemplate($deleteData: DeleteAspectTemplateInput!) {
Fixed

2022-06-10 06:36 UTC, techsmyth commented on src/domain/template/canvas-template/dto/canvas.template.dto.create.ts
> +  @MaxLength(VERY_LONG_TEXT_LENGTH)
Agreed, fixed

2022-06-10 06:39 UTC, techsmyth commented
Thanks for the thorough review. Comments in-line:

- data migration is incorrect and leads to data replication
NS> This is a judgement not a fact. We discussed to use copy on instantiation. 
- data types / dtos don't match
NS> Which
- canvases won't work with this setup as DTO size is not applied here
NS> We did not have this type before, now fixed
- one of the samples (delete-aspect-template) is wrong, and delete-canvas-template is overall missing
NS> Fixed
- template.set.resolver.mutations.ts actually contains aspect template and canvas template mutations and no templatesset mutations. It makes sense to an extent given all canvases are part of a templatesset, but in my opinion logically this is aspect / canvas template mutations. Templatesset mutations would be to alter the state of a templates set, and we don't have that at all. At the same time the canvas/aspect.template.resolver.mutations.ts are left out empty.
NS> This needs discussion. I agree it is not ideal. The issue is that at the moment authorization is only at the TemplatesSet level, not the actual templates. If we also make the authorization per template then we can address this - and this may be what is needed as otherwise the approach does not scale to lots of template types
- There are dead DTOs in the code that are not being used by any mutation
NS> which? 

I believe these all need addressing before going further with the review of the services.

2022-06-15 13:53 UTC, valentinyanakiev requested changes
Migration fails with data:

```
error: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)
    at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:375:28)
    at Socket.emit (domain.js:470:12)
    --------------------
    at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
    at MysqlQueryRunner.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:185:36)
    at step (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:143:27)
    at Object.next (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:124:57)
    at fulfilled (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)',
  sqlState: '23000',
  index: 0,
  sql: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
    "          VALUES ('e57a57b8-f111-4f55-bd87-76c5dc230ac9', NOW(), NOW(), 1, '3e8d2506-81ff-41f8-b5d6-5bfc2f6cdfbd', '5a44581c-4427-4c83-83d8-5c962984a7bb', 'knowledge', 'Please describe the knowledge that is relevant.')"
}
Migration "templatesSet1654842042827" failed, error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)
query: ROLLBACK
Error during migration run:
QueryFailedError: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)
    at QueryFailedError.TypeORMError [as constructor] (/home/valentin/source/repos/alkemio/server/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/valentin/source/repos/alkemio/server/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  query: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
    "          VALUES ('e57a57b8-f111-4f55-bd87-76c5dc230ac9', NOW(), NOW(), 1, '3e8d2506-81ff-41f8-b5d6-5bfc2f6cdfbd', '5a44581c-4427-4c83-83d8-5c962984a7bb', 'knowledge', 'Please describe the knowledge that is relevant.')",
  parameters: undefined,
  driverError: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)
      at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:375:28)
      at Socket.emit (domain.js:470:12)
      --------------------
      at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
      at MysqlQueryRunner.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:185:36)
      at step (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:114:62)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: 'ER_NO_REFERENCED_ROW_2',
    errno: 1452,
    sqlMessage: 'Cannot add or update a child row: a foreign key constraint fails (`alkemio`.`aspect_template`, CONSTRAINT `FK_66667901817dd09d5906537e088` FOREIGN KEY (`templateInfoId`) REFERENCES `template_info` (`id`) ON DELETE SET NULL ON UPDATE NO ACTION)',
    sqlState: '23000',
    index: 0,
    sql: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
      "          VALUES ('e57a57b8-f111-4f55-bd87-76c5dc230ac9', NOW(), NOW(), 1, '3e8d2506-81ff-41f8-b5d6-5bfc2f6cdfbd', '5a44581c-4427-4c83-83d8-5c962984a7bb', 'knowledge', 'Please describe the knowledge that is relevant.')"
  },
  code: 'ER_NO_REFERENCED_ROW_2',
  errno: 1452,
  sqlMessage: 'Cannot add or update a c [...]

2022-06-15 18:19 UTC, techsmyth commented
Grrr, not sure how that error got in. Should be ok now...

2022-06-16 06:04 UTC, valentinyanakiev commented
> Grrr, not sure how that error got in. Should be ok now...

It's not

```
Migration "templatesSet1654842042827" failed, error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 're able to offer, such as: what exactly can you help with, how much time can ...' at line 2
query: ROLLBACK
Error during migration run:
QueryFailedError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 're able to offer, such as: what exactly can you help with, how much time can ...' at line 2
    at QueryFailedError.TypeORMError [as constructor] (/home/valentin/source/repos/alkemio/server/src/error/TypeORMError.ts:7:9)
    at new QueryFailedError (/home/valentin/source/repos/alkemio/server/src/error/QueryFailedError.ts:9:9)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:196:37)
    at Query.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:92:8)
    at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10) {
  query: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
    "          VALUES ('ed10f49d-f46f-4299-9420-55976f5ec3ed', NOW(), NOW(), 1, 'c2624b1e-734a-4d73-9630-87b35dd18a8f', '57cf9d19-19ba-4237-866c-d300d43d459a', 'help offered', 'Provide information on the help you're able to offer, such as: what exactly can you help with, how much time can you spend, how can people reach you. Anything is much appreciated! <br/> <br/> Don't forget to use tags to increase the findability of your item. Please make sure you place the request in the right Challenge (e.g. translation issues in the 'Translation' Challenge).')",
  parameters: undefined,
  driverError: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 're able to offer, such as: what exactly can you help with, how much time can ...' at line 2
      at Query.Sequence._packetToError (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
      at Query.ErrorPacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
      at Protocol._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:291:23)
      at Parser._parsePacket (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:433:10)
      at Parser.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Parser.js:43:10)
      at Protocol.write (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:38:16)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:88:28)
      at Socket.<anonymous> (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:526:10)
      at Socket.emit (events.js:375:28)
      at Socket.emit (domain.js:470:12)
      --------------------
      at Protocol._enqueue (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/protocol/Protocol.js:144:48)
      at PoolConnection.query (/home/valentin/source/repos/alkemio/server/node_modules/mysql/lib/Connection.js:198:25)
      at MysqlQueryRunner.<anonymous> (/home/valentin/source/repos/alkemio/server/src/driver/mysql/MysqlQueryRunner.ts:185:36)
      at step (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:143:27)
      at Object.next (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:124:57)
      at fulfilled (/home/valentin/source/repos/alkemio/server/node_modules/tslib/tslib.js:114:62)
      at processTicksAndRejections (internal/process/task_queues.js:95:5) {
    code: 'ER_PARSE_ERROR',
    errno: 1064,
    sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 're able to offer, such as: what exactly can you help with, how much time can ...' at line 2",
    sqlState: '42000',
    index: 0,
    sql: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
      "          VALUES ('ed10f49d-f46f-4299-9420-55976f5ec3ed', NOW(), NOW(), 1, 'c2624b1e-734a-4d73-9630-87b35dd18a8f', '57cf9d19-19ba-4237-866c-d300d43d459a', 'help offered', 'Provide information on the help you're able to offer, such as: what exactly can you help with, how much time can you spend, how can people reach you. Anything is much appreciated! <br/> <br/> Don't forget to use tags to increase the findability of your item. Please make sure you place the request in the right Challenge (e.g. translation issues in the 'Translation' Challenge).')"
  },
  code: 'ER_PARSE_ERROR',
  errno: 1064,
  sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 're able to offer, such as: what exactly can you help with, how much time can ...' at line 2",
  sqlState: '42000',
  index: 0,
  sql: 'INSERT INTO aspect_template (id, createdDate, updatedDate, version, templatesSetId, templateInfoId, type, defaultDescription)\n' +
    "          VALUES ('ed10f49d-f46f-4299-9420-55976f5ec3ed', NOW(), NOW(), 1, 'c2624b1e-734a-4d73-9630-87b35dd18a8f', '57cf9d19-19ba-4237-866c-d300d43d459a', 'help offered', 'Provide information on the help you're able to offer, such as: what exactly can you help with, how much time can you spend, how can people reach you. Anything is much appreciated! <br/> <br/> Don't forget to use tags to increase the findability of your item. Please make sure you place the request in the right Challenge (e.g. translation issues in the 'Translation' Challenge).')"
}
```

2022-06-16 06:04 UTC, valentinyanakiev commented
I'd suggest trying to run this on a meaningful dataset...

2022-06-16 11:25 UTC, valentinyanakiev approved these changes

2022-06-16 11:27 UTC, merged