Redis
alkem-io/server pull request #1997
Opened 2022-06-16 12:24 UTC by valentinyanakiev

2022-06-17 07:35 UTC, hero101 submitted a review, later dismissed

2022-06-20 07:07 UTC, hero101 requested changes
Suggestions aside, I am not sure you need to use `useMocker` if you are providing the dependencies mocked in each test.
Also, take a look at [this](https://jestjs.io/docs/configuration#automock-boolean).

2022-06-20 07:07 UTC, hero101 commented on src/domain/communication/communication/communication.service.spec.ts
> +        {
extract this provider and replace it inline like the others

2022-06-20 12:28 UTC, valentinyanakiev commented on src/domain/communication/communication/communication.service.spec.ts
> +        {
Fixed with a factory in https://github.com/alkem-io/server/pull/1997/commits/5433ab6f5485f5d2000b8369104266935623c945

2022-06-20 12:39 UTC, hero101 approved these changes

2022-06-20 12:51 UTC, merged