Cached AgentInfo
alkem-io/server pull request #2006
Opened 2022-06-22 05:43 UTC by valentinyanakiev

2022-06-23 09:26 UTC, hero101 requested changes

2022-06-23 09:26 UTC, hero101 commented on src/domain/agent/agent/agent.cache.service.ts
> +  private async getAgentInfoCacheKey(email: string): Promise<string> {
the return type is incorrect

2022-06-23 09:26 UTC, hero101 commented on src/domain/agent/agent/agent.cache.service.ts
> +        ttl: 1,
Extract this one and the one in `update` to a constant or config.
isn't 1 second too small? I think boosting it a little will bring more performance benefits

2022-06-23 09:26 UTC, hero101 commented on src/domain/agent/agent/agent.cache.service.ts
> +    const users: { email: string }[] = await getConnection().query(
any reason you did not use the agent repo here?

2022-06-23 09:26 UTC, hero101 commented on src/domain/community/user/user.service.ts
> +      .getRawMany<any>()
put the correct type here

2022-06-23 09:26 UTC, hero101 commented on src/domain/community/user/user.service.ts
> +      .then(agents => {
`agents` seems misleading here

2022-06-23 09:26 UTC, hero101 commented on src/domain/community/user/user.service.ts
> +            `Unable to load Agent for User: ${email}`,
agent OR credentials?

2022-06-23 09:26 UTC, hero101 commented on src/domain/community/user/user.service.ts
> +        if (!agents) {
The type suggests this can't be `undefined`, but an `empty` array.

2022-06-23 09:49 UTC, valentinyanakiev commented on src/domain/agent/agent/agent.cache.service.ts
> +    const users: { email: string }[] = await getConnection().query(
You can't use the agent repo, as you need the email. I do that via right join, which is unsupported by ORM. Normally, that can be done via having the query + repo + service call in users service / module, but that would require importing the users module and results in a circular dependency user <--> agent.

2022-06-24 15:53 UTC, me-andre commented on src/core/authentication/authentication.service.ts
> +    const cachedAgentInfo = await this.agentCacheService.getAgentInfoFromCache(
If this approach is lazily initialized cache entry, i.e. no cache on read - creating one and returning, I'd wrap this whole thing in a lock (such as redis lock). Pseudo code:
```ruby
lock_resource :resource
saved = nil
return saved if saved = try_get()
saved = store(compute())
release_resource :resource
return saved
```

This will eliminate situations when there's no cache and multiple concurrent requests are accessing the same cache entry: they will all start producing the value until the first one succeeds and updates the cache.

2022-06-24 15:55 UTC, me-andre commented on src/domain/agent/agent/agent.cache.service.ts
> +    return await this.cacheManager.set<AgentInfo>(
Can we reuse `setAgentInfoCache()` here?

2022-06-24 16:01 UTC, me-andre commented on src/domain/agent/agent/agent.cache.service.ts
> +      WHERE \`a\`.\`id\` = '${agentId}'`
If I assume correctly that `getConnection()` provides a raw driver interface, then we should look for a safer way of passing query params.
I didn't work with mysql in node, but in `pg` it looked like this:
```js
await query('SELECT * FROM tableName WHERE id = $1', [params.id])
```

As a bonus, the need to escape backticks may go away.

2022-06-27 06:27 UTC, hero101 commented on src/domain/agent/agent/agent.cache.service.ts
> +      WHERE \`a\`.\`id\` = '${agentId}'`
the second param of the `query` method is params.

2022-06-28 13:15 UTC, valentinyanakiev commented on src/core/authentication/authentication.service.ts
> +    const cachedAgentInfo = await this.agentCacheService.getAgentInfoFromCache(
Will be addressed in https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/server/2021

2022-06-28 13:15 UTC, merged