LifecycleTemplate; improved typing on Lifecycles in general
alkem-io/server pull request #2041
Opened 2022-07-10 06:25 UTC by techsmyth

New entity: LifecycleTemplate

Updated TemplatesSet to hold an array of LifecycleTemplates

New scalar type to represent LifecycleDefinitions

New internal server type for LifecycleDefinitions

New mutation to allow updating of the LifecycleDefinition on a Challenge

New privilege type: UPDATE_LIFECYCLE, currently only assigned to global admins.

Sample mutations:
- adding LifecycleTemplate
- updating lifecycle on Challenge

2022-07-19 13:44 UTC, hero101 approved these changes

2022-07-19 13:44 UTC, hero101 commented on src/common/interfaces/lifecycle.definition.interface.ts
> +}
Can't we do something about those types? What data is in there?

2022-07-19 13:44 UTC, hero101 commented on src/domain/common/lifecycle/lifecycle.service.ts
> +  deserializeLifecycleDefinition(value: string): ILifecycleDefinition {
util function

2022-07-19 13:44 UTC, hero101 commented on src/domain/common/lifecycle/lifecycle.service.ts
> +  serializeLifecycleDefinition(definition: ILifecycleDefinition): string {
util function

2022-07-19 13:44 UTC, hero101 commented on src/domain/template/lifecycle-template/dto/lifecycle.template.dto.create.ts
> +  @IsOptional()
Why optional?

2022-07-19 13:44 UTC, hero101 commented on src/domain/challenge/challenge/challenge.resolver.mutations.ts
> +    const challenge = await this.challengeService.getChallengeOrFail(
just the authorization is needed here

2022-07-19 13:44 UTC, hero101 commented on src/domain/challenge/challenge/challenge.service.ts
> +    const challenge = await this.getChallengeOrFail(challengeData.challengeID);
you just need the id here

2022-07-19 13:44 UTC, hero101 commented on src/domain/challenge/challenge/challenge.service.ts
> +    await this.lifecycleService.deleteLifecycle(oldLifecycle.id);
this method impl can be changed to use the delete method of the repo, by just providing the id. Fetching the entity as in the current impl is not required.

2022-07-19 13:44 UTC, hero101 commented on src/domain/collaboration/opportunity/opportunity.service.ts
> +    return await this.save(opportunity);
Create, assign new lifecycle, delete old lifecycle vs just updating the existing one?

2022-07-19 13:44 UTC, hero101 commented on src/domain/template/lifecycle-template/lifecycle.template.service.ts
> +    await this.templateBaseService.deleteEntities(lifecycleTemplate);
cascade on delete vs `deleteEntities`

2022-07-21 06:21 UTC, hero101 requested changes
A complete review.
Migration tested on local.

2022-07-21 06:21 UTC, hero101 commented on src/domain/template/template-info/template.info.service.ts
> +    const templateInfo = await TemplateInfo.findOne(
`templateInfoRepository`

2022-07-22 10:22 UTC, hero101 approved these changes

2022-07-22 10:24 UTC, hero101 commented
@Comoque1 please test this if you have the capacity.
The PR should be merged after it's tested because it introduces a lot of changes and additions.
I have reviewed and manually tested some cases.

2022-07-26 08:14 UTC, valentinyanakiev approved these changes

2022-07-29 06:47 UTC, merged