Moved aspects / canvases counts to collaboration
alkem-io/server pull request #2084
Opened 2022-08-16 08:38 UTC by techsmyth

I saw that the activity was failing on opportunity so put in a fix. Found that since my merge another fix had gone in. 

However there was still the issue that the BaseChallenge service should never need to be importing the CanvasModule or AspectModule - these should only be known at the collaboration entity level.

2022-08-16 08:54 UTC, alstojanovic submitted a review, later dismissed

2022-08-16 10:02 UTC, valentinyanakiev requested changes
I want to review it.

2022-08-16 11:09 UTC, techsmyth commented
Great if you can. We do need to take care that the module dependencies are also properly layered, so it is a red flag is the baseChallenge service has knowledge of canvasService etc.

2022-08-17 06:15 UTC, valentinyanakiev approved these changes

2022-08-17 06:24 UTC, merged