Lifecycle template creation
alkem-io/server pull request #2087
Opened 2022-08-17 13:36 UTC by valentinyanakiev

- mandatory lifecycle template selection on challenge / opportunity creation
- check whether a lifecycle template of specific type, e.g. CHALLENGE / OPPORTUNITY etc is the last one of its type in the set - last template can NOT be deleted and results in an exception
   - logic is in the lifecycletemplate service. Logically, this belongs to the templatesSet service but there are no remove / delete operations there for any of lifecycleTemplate / aspectTemplate / canvasTemplate so I have kept the following logic
- defaulting to the first found template of a type in Opp --> Challenge conversion if none is provided (parameter for the template is set as `optional`)
- templateSet is mandatory for CreateChallenge / CreateOpportunity DTOs

2022-08-17 14:05 UTC, techsmyth requested changes
The refactoring makes sense and looks clean.

I would suggest that we use the correct name in the updated DTOs and code i.e. InnovationFlow. "Lifecycle" is then the type. 

Also please then also update the updateChallengeLifecycle mutation to be called "updateChallengeInnovationFlow", renaming the associated DTO + containing field that specified the template ID. Ditto for Opportunity InnovationFlow template.

2022-08-17 14:05 UTC, techsmyth commented on src/domain/challenge/challenge/challenge.service.ts
> +        challengeData.lifecycleTemplateID,
Suggest to call it innovationFlowTemplateID

2022-08-17 14:05 UTC, techsmyth commented on src/domain/challenge/challenge/dto/challenge.dto.create.ts
> +  lifecycleTemplateID!: string;
call it innovationFlowTemplateID - the type is Lifecycle...

2022-08-17 14:05 UTC, techsmyth commented on src/domain/challenge/hub/hub.service.ts
> +  async getDefaultLifecycleTemplate(
Ditto re name...

2022-08-17 14:05 UTC, techsmyth commented on src/domain/challenge/hub/hub.service.ts
> +    if (selectableLifecycleTemplates.length === 0)
Ditto...

2022-08-18 08:34 UTC, alstojanovic approved these changes

2022-08-18 08:34 UTC, alstojanovic commented on src/common/enums/authorization.privilege.ts
> +  UPDATE_INNOVATION_FLOW = 'update-lifecycle',
Should we also rename the 'update-lifecycle' literal to 'update-innovation-flow'?

2022-08-18 08:49 UTC, merged