Callout published event
alkem-io/server pull request #2131
Opened 2022-08-31 14:18 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2022-08-31 18:34 UTC, techsmyth requested changes, later dismissed
Looks good. Primary comment is to be consistent with it being CALLOUT_PUBLISHED.

2022-08-31 18:34 UTC, techsmyth commented on src/common/enums/user.preference.type.ts
> +  NOTIFICATION_CALLOUT_CREATED = 'NotificationCalloutCreated',
This should also be CALLOUT_PUBLISHED, also in the value.

2022-08-31 18:34 UTC, techsmyth commented on src/core/microservices/event-payloads/callout.published.event.payload.ts
> +    displayName: string;
I would also add the description so that it is also available in the email template.

2022-08-31 18:34 UTC, techsmyth commented on src/core/microservices/notifications.payload.builder.ts
> +import { ICallout } from '@domain/collaboration/callout';
Make the import specific to the callout.interface class

2022-08-31 18:34 UTC, techsmyth commented on src/core/microservices/notifications.payload.builder.ts
> +        displayName: callout.displayName,
add the description

2022-08-31 18:34 UTC, techsmyth commented on src/migrations/1661850289882-callout-notification-preferences.ts
> +        displayName: 'New callout created',
New callout published

2022-08-31 18:34 UTC, techsmyth commented on src/migrations/1661850289882-callout-notification-preferences.ts
> +          'Receive a notification when a callout is created in a community I am a member of',
Receive a notification when a Callout is published in a community I am a member of

2022-08-31 18:34 UTC, techsmyth commented on src/migrations/1661850289882-callout-notification-preferences.ts
> +        type: UserPreferenceType.NOTIFICATION_CALLOUT_CREATED,
NOTIFICATION_CALLOUT_PUBLISHED

2022-08-31 18:34 UTC, techsmyth commented on src/migrations/1661850289882-callout-notification-preferences.ts
> +      PreferenceType.NOTIFICATION_CALLOUT_CREATED,
PUBLISHED

2022-09-01 08:47 UTC, alstojanovic approved these changes

2022-09-01 09:25 UTC, merged