Improved migration utils; recommendation data issues addressed
alkem-io/server pull request #2773
Opened 2023-05-02 15:07 UTC by hero101

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2023-05-02 16:33 UTC, hero101 commented
To be merged with  https://github.com/alkem-io/client-web/pull/3922

2023-05-03 07:30 UTC, valentinyanakiev requested changes
Two minor comments to be fixed, other than that migration worked on production data.

2023-05-03 07:30 UTC, valentinyanakiev commented on src/migrations/types/callout-state.ts
> +export enum CalloutState {
Please move this state as part of the migration using it. The state is a snapshot in time and if the states change, you change this enum, and then re-running the migrations will change its original behavior, which is not intended.

2023-05-03 07:30 UTC, valentinyanakiev commented on src/migrations/types/callout-visiblity.ts
> +export enum CalloutVisibility {
Same as previous one.

2023-05-03 07:58 UTC, valentinyanakiev approved these changes

2023-05-03 07:58 UTC, merged