updated mutation for innovationFlow to specify optionally the set of visibleStates
alkem-io/server pull request #3024
Opened 2023-07-13 14:54 UTC by techsmyth

…innovationflow visible states

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2023-07-13 21:32 UTC, valentinyanakiev requested changes
I probably don't understand something, but I don't believe this is sufficient, nor that it will work. I keep seeing the `innovationFlow.profile.Id` being provided to the `UpdateProfileSelectTagsetInput`, but this is not the profileID of the tagsets filtering the `Callouts`. Each `Callout` has a classification tagset with name `flow-state` and this tagset has profileID the profileID of the `Callout`. So to update what is actually driving the filtering, we need to provide the `Callout` profileID. Essentially, we need to loop through all `Callouts` for a specified `Collaboration` linked to a `Challenge` or `Opportunity`. We change the `InnovationFlow` of that `Challenge` or `Opportunity`, we need to loop through all `flow-state` tagsets in `Callouts`. I don't see that here. Or I am missing something big time.

2023-07-14 05:48 UTC, techsmyth commented
I think it is the relationship between the tagset and the tagset-template that is not being considered. 

The allowedValues on a tagset is a calculated field, with the result being the allowedValues field on the TagsetTemplate. 

Both the flow-state tagset on the InnovationFlow and the flow-state tagset on each Callout all point back to **the same** tagset-template entity.

So updating the single tagset-template also updates the allowed values on all the tagsets on the callouts.

So I think the above should work...

2023-07-14 06:32 UTC, valentinyanakiev commented
> I think it is the relationship between the tagset and the tagset-template that is not being considered.
> 
> The allowedValues on a tagset is a calculated field, with the result being the allowedValues field on the TagsetTemplate.
> 
> Both the flow-state tagset on the InnovationFlow and the flow-state tagset on each Callout all point back to **the same** tagset-template entity.
> 
> So updating the single tagset-template also updates the allowed values on all the tagsets on the callouts.
> 
> So I think the above should work...

While what you are saying is true, that will work for creating `new` entities. It won't updated `existing` ones. Updating the `tagsetTemplate` value goes through `updateSelectTagset` and while it indeed updates the `tagsetTemplate`, there is nothing for updating the `tagsets` `templated` by it..

2023-07-17 14:00 UTC, valentinyanakiev approved these changes

2023-07-17 14:00 UTC, merged