added initial prototype code for modules to support callout templates
alkem-io/server pull request #3192
Opened 2023-09-03 18:08 UTC by techsmyth

New entities / modules:
* CalloutFraming
* CalloutResponseDefaults
* CalloutResponsePolicy
* CalloutTemplate

Todo:
* samples for working with the api
* migration to create the new tables etc
* test, test, test

2023-09-18 14:05 UTC, hero101 requested changes
I have left some notes that we need to discuss and also general notes:
- passing a profile to the framing when creating a template does not feel right. Furthermore, you have to provide a display name to that profile, which feels even stranger.
- the responseDefaults input is mandatory but nothing in IS. I am guessing it needs to be also optional or some sort of validation to provide at least one or only one
- I believe the updating API can be improved. Updating the framing of a template requires it's ID, but it should be already known by the backend so it's not really required.

The create and delete work fine.

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-framing/callout.framing.entity.ts
> +  content?: string;
The typeorm definition says non-nullable, but the class field is nullable.

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-framing/callout.framing.interface.ts
> +  content?: string;
I think it's a good idea to sync this field with the entity definition

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-framing/callout.framing.service.ts
> +    calloutFraming.authorization = new AuthorizationPolicy();
what about profile

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-response-defaults/callout.response.defaults.entity.ts
> +  whiteboardContent?: string;
The entity definition is `nullable: false`

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-response-defaults/callout.response.defaults.entity.ts
> +  whiteboardContent?: string;
The entity definition is `nullable: false`

2023-09-18 14:05 UTC, hero101 commented on src/domain/collaboration/callout-response-defaults/callout.response.defaults.service.ts
> +    return calloutResponseDefaults;
what about `whiteboardContent`?

2023-09-19 07:25 UTC, techsmyth commented on src/domain/collaboration/callout-framing/callout.framing.entity.ts
> +  content?: string;
nullable should be true

2023-09-19 07:26 UTC, techsmyth commented on src/domain/collaboration/callout-framing/callout.framing.service.ts
> +    calloutFraming.authorization = new AuthorizationPolicy();
yikes

2023-09-19 07:26 UTC, techsmyth commented on src/domain/collaboration/callout-framing/callout.framing.entity.ts
> +  content?: string;
field to be called whiteboardContent

2023-09-19 07:26 UTC, techsmyth commented on src/domain/collaboration/callout-response-defaults/callout.response.defaults.entity.ts
> +  whiteboardContent?: string;
nullable: true

2023-09-19 07:27 UTC, techsmyth commented on src/domain/collaboration/callout-response-defaults/callout.response.defaults.service.ts
> +    return calloutResponseDefaults;
good catch

2023-09-19 07:33 UTC, techsmyth commented
@hero101 please rename Response to be Contribution

2023-09-19 13:23 UTC, hero101 approved these changes

2023-09-19 13:24 UTC, merged