added type for whiteboard content
alkem-io/server pull request #3203
Opened 2023-09-06 16:48 UTC by techsmyth

Used on all DTOs, fields where whiteboard content is being handled.

2023-09-11 13:56 UTC, me-andre commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +  validate = (value: any) => {
As far as I see, this can be a method

2023-09-11 13:57 UTC, me-andre commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +  validate = (value: any) => {
(or maybe a class method even)

2023-09-14 05:27 UTC, techsmyth commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +  validate = (value: any) => {
You mean to move the function to be at the class level? Not sure that adds any value as this method should not be public and is not re-used.

2023-09-18 09:20 UTC, hero101 requested changes
I also believe the new scalar must be included in the codegen.yml of the client.

2023-09-18 09:20 UTC, hero101 commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +        `Whiteboard content is not string: ${value}`,
Please don't throw the whole value in the exception.

2023-09-18 09:20 UTC, hero101 commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +  validate = (value: any) => {
`validate` is already a public class method - It can be private, but I don't see any other issue than that.

2023-09-18 10:59 UTC, me-andre commented on src/domain/common/scalars/scalar.whiteboard.content.ts
> +  validate = (value: any) => {
Sorry for not being clear, what I meant is that I would expect that method to be `static` (or extracted outside as a utility function). That is a matter of code style though.

2023-09-18 11:12 UTC, hero101 approved these changes

2023-09-18 11:12 UTC, me-andre approved these changes

2023-09-18 11:14 UTC, merged