If user exists, external invitation creates a normal one instead
alkem-io/server pull request #3861
Opened 2024-04-23 14:26 UTC by me-andre

### Describe the background of your pull request

What does your pull request do? Does it solve a bug (which one?), add a feature?

### Additional context

Add any other context

### Governance 

- [ ] Documentation is added
- [ ] Test cases are added or updated

By submitting this pull request I confirm that:
- I've read the contributing document https://github.com/alkem-io/.github/blob/master/CONTRIBUTING.md.
- I've read and understand the Code of Conduct https://github.com/alkem-io/.github/blob/master/CODE_OF_CONDUCT.md.
- I understand that any contributions or suggestions I made may make it into the actual code. I've read the License 
     https://github.com/alkem-io/Coordination/blob/master/LICENSE.
- I understand that submitting the pull request requires agreeing to and signing the contributor license agreement.

2024-04-23 14:28 UTC, me-andre commented
Please review this one as well https://github.com/alkem-io/client-web/pull/5986

2024-04-25 10:08 UTC, hero101 requested changes

2024-04-25 10:08 UTC, hero101 commented on src/domain/community/community/community.resolver.mutations.ts
> +    return Promise.all(
I believe some handling is required here. I am not sure what will happen if one invitation fails.

2024-04-25 10:08 UTC, hero101 commented on src/domain/community/community/community.resolver.mutations.ts
> +  ): Promise<IInvitation | IInvitationExternal> {
It bugs me that the mutation is named `inviteExternalUser...` but you are allowed to use it on anyone.

2024-04-25 10:27 UTC, me-andre commented on src/domain/community/community/community.resolver.mutations.ts
> +    return Promise.all(
Same as before: an exception is thrown
Not same as before: all non-failed invitation would attempt to complete (which is better imo because we may not want to end in undefined state)

2024-04-25 10:29 UTC, me-andre commented on src/domain/community/community/community.resolver.mutations.ts
> +  ): Promise<IInvitation | IInvitationExternal> {
Yepp, would you suggest a rename? It's actually invites by email regardless of whether a user exists, so maybe `inviteForCommunityMembershipByEmail`?

2024-04-25 10:31 UTC, hero101 commented on src/domain/community/community/community.resolver.mutations.ts
> +  ): Promise<IInvitation | IInvitationExternal> {
Yes! That's even better.

2024-04-25 13:54 UTC, hero101 approved these changes

2024-04-25 14:00 UTC, merged