Notification on space creation
alkem-io/server pull request #4206
Opened 2024-07-03 06:56 UTC by EmiliaPavlova

When a top level space is created, send a notification to all License Managers with:

- Date/time
- Space nameid / link to space
- host

2024-07-04 07:41 UTC, ccanos requested changes

2024-07-04 07:41 UTC, ccanos commented on src/services/adapters/notification-adapter/notification.payload.builder.ts
> +      )) as Space;
can we avoid this `as` here ?

2024-07-04 07:48 UTC, EmiliaPavlova commented on src/services/adapters/notification-adapter/notification.payload.builder.ts
> +      )) as Space;
removed

2024-07-04 17:49 UTC, ccanos approved these changes, later dismissed

2024-07-05 05:57 UTC, techsmyth approved these changes
Approving again after fixing build

2024-07-05 05:57 UTC, merged