added type to storage aggregator, with migration
alkem-io/server pull request #4375
Opened 2024-08-07 15:35 UTC by techsmyth

Todo: use the type to correctly return the parent entity information, especially for organizations / users

2024-08-08 11:32 UTC, valentinyanakiev requested changes
Some comments inline.
I also suggest this is covered with API tests before we take it in, then we will make sure it works and it will continue working in the future.

2024-08-08 11:32 UTC, valentinyanakiev commented on src/services/infrastructure/storage-aggregator-resolver/storage.aggregator.resolver.service.ts
> +      throw new NotImplementedException(
this is not `NotImplementedException`, more of an `EntityNotFoundException`

2024-08-08 11:32 UTC, valentinyanakiev commented on src/services/infrastructure/storage-aggregator-resolver/storage.aggregator.resolver.service.ts
>        throw new NotImplementedException(
this is not NotImplementedException, more of an EntityNotFoundException

2024-08-08 11:32 UTC, valentinyanakiev commented on src/services/infrastructure/storage-aggregator-resolver/storage.aggregator.resolver.service.ts
> +      throw new NotImplementedException(
this is not NotImplementedException, more of an EntityNotFoundException

2024-08-08 11:32 UTC, valentinyanakiev commented on src/services/infrastructure/storage-aggregator-resolver/storage.aggregator.resolver.service.ts
> +      throw new NotImplementedException(
this is not NotImplementedException, more of an EntityNotFoundException

2024-08-08 11:32 UTC, valentinyanakiev commented on src/migrations/1723036109999-storageAggregatorType.ts
> +    );
I don't see logic about the `Platform` `StorageAggregator`

2024-08-09 10:20 UTC, techsmyth commented
@valentinyanakiev  comments are I think addressed. Re api test, would not hold this up for that as parentEntity field is not really used outside of spaces for now, so this was more about stopping getting a ton of errors in the logs rather than getting a field we depend on robust.

2024-08-09 11:40 UTC, valentinyanakiev requested changes
One final change before we merge that - level on `ParentEntity` field resolver returns `SPACE` for `Platform`, `Organization`, `Account`, `User`. That doesn't make any sense - it should be nullable and the field should be null, in case it is not relevant at all for the parent entity.

2024-08-09 14:55 UTC, valentinyanakiev approved these changes

2024-08-09 14:59 UTC, merged