"flow-state" tagset template is  created in advanced
alkem-io/server pull request #4397
Opened 2024-08-12 11:51 UTC by hero101

2024-08-12 12:42 UTC, hero101 commented
drafting because I found a bug while using the client

2024-08-12 12:59 UTC, hero101 commented
Turns out it was due to corrupted data/schema - ready for review again.

2024-08-19 08:21 UTC, valentinyanakiev requested changes
Doesn't work for me, tested with createing a subspace of an existing space.

I get a lot of "Unable to load tagsetTemplate for Tagset:...".
When I create a subspace with the code from `develop`, it works. This will introduce a regression.

2024-08-20 14:33 UTC, valentinyanakiev approved these changes

2024-08-20 14:33 UTC, merged