Domain model
alkem-io/server pull request #965
Opened 2021-05-13 14:01 UTC by techsmyth

2021-05-17 10:44 UTC, atstojanov commented
Running migrations are failing: `Error: ER_TABLE_EXISTS_ERROR: Table 'query-result-cache' already exists`

2021-05-18 21:02 UTC, Comoque1 commented
"Project" cannot be created.

Repro steps:
1. Create Challenge
2. Create ChildChallenge
3. CreateProject - request fails
`"message": "ER_NO_DEFAULT_FOR_FIELD: Field 'ecoverseID' doesn't have a default value"`

![image](https://user-images.githubusercontent.com/23620658/118723021-8b9c8400-b835-11eb-98eb-befb27fbf607.png)

2021-05-19 08:28 UTC, Comoque1 commented
Reference cannot be created as part of createChallenge gql request.
![image](https://user-images.githubusercontent.com/23620658/118781106-5e7fbe00-b895-11eb-9a41-d9df84652956.png)

2021-05-19 09:48 UTC, techsmyth commented
@Comoque1 re bugs raised:
- just fixed the references on challenge creation: 82f8cd4604e3048cb66a17d85e71721163d1d84b
- the project creation bug: please note this and pick it up when we merge in the domain-model-plus branch

2021-05-20 10:49 UTC, atstojanov commented
When trying to create new Project  `ER_NO_DEFAULT_FOR_FIELD: Field 'ecoverseID' doesn't have a default value`.

2021-05-20 11:13 UTC, atstojanov commented
> When trying to create new Project `ER_NO_DEFAULT_FOR_FIELD: Field 'ecoverseID' doesn't have a default value`.

Maybe the problem is in my machine, because I'm passing as `parentId` the `opportunityId` (`challengeID`) instead of `collaborationID`.

So the `parentId` is not informative enough for the developer to understand what value must be passed. Either change the field to `collaborationId` (best variant) or add description what is expected (worst).

2021-05-20 11:24 UTC, atstojanov commented
TypeOrm Error: `Relation "ecoverse" was not found; please check if it is correct and really exists in your entity.`

2021-05-20 11:37 UTC, atstojanov commented on src/domain/collaboration/project/project.resolver.fields.ts
> +  @ResolveField('lifecycle2', () => ILifecycle, {
Why `lifecycle2` after every other entity has property `lifecycle`?

2021-05-20 11:56 UTC, atstojanov commented
`Activity` is missing from `Opportunity`

2021-05-20 12:03 UTC, valentinyanakiev requested changes
Still a few minor tweaks / changes required, comments inline.

2021-05-20 12:03 UTC, valentinyanakiev commented on src/app.module.ts
> -        synchronize: false,
should be false

2021-05-20 12:03 UTC, valentinyanakiev commented on src/common/enums/logging.context.ts
> +  COLLABORATION = 'collaboration',
collaboration should be opportunity

2021-05-20 12:03 UTC, valentinyanakiev commented on src/domain/common/lifecycle/lifecycle.interface.ts
> +@ObjectType('Lifecycle2')
Rename 'Lifecycle2'

2021-05-20 13:08 UTC, techsmyth commented on src/domain/collaboration/project/project.resolver.fields.ts
> +  @ResolveField('lifecycle2', () => ILifecycle, {
Agreed

2021-05-20 13:15 UTC, techsmyth commented on src/common/enums/logging.context.ts
> +  COLLABORATION = 'collaboration',
disagree, opportunity is part of collaboration

2021-05-20 13:38 UTC, valentinyanakiev approved these changes

2021-05-20 13:41 UTC, merged